[package]
name = "MultiplicationTables"
version = "0.1.0"
authors = ["Dari <Dari@dari.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
